<?php

return [
    'version' => 'content_angle_engine_v1',

    'guardrails' => [
        'professionality_priority' => 'Prima alza la qualita percepita del brand, poi cerca reach ed engagement.',
        'hard_avoid' => [
            'Hook trash, clickbait urlato o formule da fuffa marketer.',
            'Promesse assolute, risultati garantiti o urgenza finta.',
            'Frasi che trattano il brand come un guru o una agenzia che parla in terza persona.',
            'Trend imitati in modo servile o meme scollegati dal contesto reale del brand.',
        ],
        'banned_hook_fragments' => [
            'nessuno te lo dice',
            'ti stanno mentendo',
            'il trucco definitivo',
            'diventa virale subito',
            'risultati garantiti',
            'segreto che',
            'assurdo ma vero',
            'hackerare l algoritmo',
        ],
    ],

    'cta_modes' => [
        'consultative_soft' => 'Invito naturale a DM, call o confronto qualificato senza pressione artificiale.',
        'save_or_share' => 'Chiudi con un invito a salvare o condividere il contenuto per utilita reale.',
        'comment_with_point_of_view' => 'Chiudi con una domanda o presa di posizione che stimola commenti utili.',
        'dm_or_click_soft' => 'Porta verso DM o click con tono consulenziale, non promozionale aggressivo.',
        'reply_with_story' => 'Invita a rispondere con esperienza personale o caso vissuto.',
    ],

    'platform_openings' => [
        'instagram' => [
            'post' => 'Prima riga fermascroll, seconda riga dettaglio concreto, terza riga payoff o punto di vista.',
            'carousel' => 'Cover con promessa chiara, sviluppo in 3-5 card utili, chiusura con takeaway o CTA soft.',
            'reel' => '0-1.5s contrasto visivo o claim breve, 1.5-3s contesto concreto, poi sviluppo rapido e payoff leggibile.',
            'story' => 'Apertura immediata e verticale mobile-first, messaggio sintetico con invito leggero alla risposta.',
            'video' => 'Parti da un dettaglio reale o gesto riconoscibile, poi fai evolvere il contenuto con ritmo social.',
        ],
        'facebook' => [
            'post' => 'Apri con scena o problema riconoscibile, poi porta il valore in modo caldo e leggibile.',
            'carousel' => 'Prima card con promessa concreta, sviluppo semplice e chiusura con CTA relazionale.',
            'reel' => 'Hook visivo pulito, contesto umano, payoff pratico o emotivo facile da commentare.',
            'story' => 'Apertura diretta e familiare, uno snodo centrale chiaro e CTA breve.',
            'video' => 'Parti dal momento piu umano o utile, poi costruisci fiducia prima della CTA.',
        ],
        'linkedin' => [
            'post' => 'Apri con insight, errore o tensione decisionale; subito dopo reframe concreto e implicazione pratica.',
            'carousel' => 'Cover con tesi netta, sviluppo con criterio operativo o mini-framework, chiusura con next step chiaro.',
            'reel' => 'Hook professionale e rapido, dato di contesto o osservazione di campo, payoff applicabile.',
            'story' => 'Apertura breve e professionale, focalizzata su un singolo insight o punto di vista.',
            'video' => 'Apri con problema reale o insight controintuitivo, poi vai dritto su applicazione e prova.',
        ],
        'tiktok' => [
            'post' => 'Apri con curiosita pulita o frame inusuale, poi chiarisci subito il valore per non sembrare bait.',
            'carousel' => 'Prima slide con contrasto o domanda forte, sviluppo rapido, chiusura con payoff condivisibile.',
            'reel' => '0-1s pattern interrupt brand-safe, 1-3s promessa concreta, 3-8s sviluppo nativo e payoff finale.',
            'story' => 'Apri immediatamente sul punto piu curioso ma chiarisci il senso entro pochi secondi.',
            'video' => 'Hook rapido e nativo, sviluppo corto e payoff leggibile senza perdere credibilita.',
        ],
    ],

    'patterns' => [
        'authoritative' => [
            [
                'key' => 'expert_reframe',
                'family' => 'authority_problem_reframe',
                'platforms' => ['linkedin', 'instagram', 'facebook'],
                'formats' => ['post', 'carousel', 'reel', 'video'],
                'goals' => ['awareness', 'trust', 'lead', 'conversion'],
                'trend_relevance' => ['low', 'medium'],
                'priority' => 0.92,
                'primary_template' => '{audience_label}: {pain_statement}. {authority_reframe}.',
                'alternative_template' => '{authority_anchor}: {desire_statement} richiede {proof_focus}.',
                'narrative_template' => 'Apri con una convinzione debole su {topic}, ribaltala con criterio concreto e chiudi con la scelta piu intelligente da fare ora.',
                'shareability_driver' => 'Reframe utile da salvare o inoltrare a chi decide.',
            ],
            [
                'key' => 'decision_filter',
                'family' => 'decision_criteria',
                'platforms' => ['linkedin', 'instagram'],
                'formats' => ['post', 'carousel', 'reel'],
                'goals' => ['trust', 'lead', 'conversion'],
                'trend_relevance' => ['low', 'medium'],
                'priority' => 0.88,
                'primary_template' => 'Prima di {desire_outcome}, guarda {decision_filter}.',
                'alternative_template' => 'Il punto non e {false_shortcut}: e {proof_focus}.',
                'narrative_template' => 'Mostra il filtro decisionale che separa una scelta superficiale da una solida su {topic}.',
                'shareability_driver' => 'Filtro decisionale che aumenta commenti qualificati e salvataggi.',
            ],
        ],
        'educational' => [
            [
                'key' => 'saved_checklist',
                'family' => 'educational_takeaway',
                'platforms' => ['instagram', 'facebook', 'linkedin'],
                'formats' => ['post', 'carousel', 'reel', 'video'],
                'goals' => ['awareness', 'trust', 'engagement'],
                'trend_relevance' => ['low', 'medium'],
                'priority' => 0.9,
                'primary_template' => '{desire_statement}: inizia da {proof_focus}.',
                'alternative_template' => 'Se vuoi {desire_outcome}, evita {false_shortcut}.',
                'narrative_template' => 'Apri con beneficio concreto, sviluppa in passaggi utili e chiudi con takeaway salvabile.',
                'shareability_driver' => 'Contenuto pratico da salvare e condividere con il team.',
            ],
            [
                'key' => 'simple_framework',
                'family' => 'clarity_framework',
                'platforms' => ['instagram', 'linkedin', 'facebook'],
                'formats' => ['carousel', 'post', 'reel'],
                'goals' => ['awareness', 'trust'],
                'trend_relevance' => ['low', 'medium'],
                'priority' => 0.84,
                'primary_template' => 'Tre segnali che ti dicono se {topic} sta davvero funzionando.',
                'alternative_template' => 'Il modo piu semplice per leggere {topic} senza complicarti il lavoro.',
                'narrative_template' => 'Semplifica {topic} in pochi indicatori o passaggi leggibili e applicabili subito.',
                'shareability_driver' => 'Framework leggero che trasforma complessita in chiarezza.',
            ],
        ],
        'trend-aware' => [
            [
                'key' => 'brand_safe_trend_reframe',
                'family' => 'trend_translation',
                'platforms' => ['instagram', 'tiktok', 'facebook', 'linkedin'],
                'formats' => ['reel', 'video', 'post', 'carousel'],
                'goals' => ['engagement', 'awareness', 'trust'],
                'trend_relevance' => ['medium', 'high'],
                'priority' => 0.93,
                'primary_template' => 'Il formato che sta girando ora funziona solo se {proof_focus}.',
                'alternative_template' => 'Se prendi il trend e lo traduci bene, {desire_statement}.',
                'narrative_template' => 'Apri sul trend o sul format del momento, chiarisci subito il punto di vista del brand e fai emergere un takeaway proprietario.',
                'shareability_driver' => 'Modernita percepita senza perdere credibilita.',
            ],
            [
                'key' => 'reactive_with_takeaway',
                'family' => 'reactive_commentary',
                'platforms' => ['instagram', 'tiktok', 'linkedin'],
                'formats' => ['reel', 'video', 'post'],
                'goals' => ['engagement', 'awareness'],
                'trend_relevance' => ['high'],
                'priority' => 0.89,
                'primary_template' => 'Tutti stanno guardando {topic}, ma il punto utile e questo: {proof_focus}.',
                'alternative_template' => '{curiosity_statement}. Ecco come leggerlo senza sembrare in ritardo sul trend.',
                'narrative_template' => 'Usa il tema caldo come porta d ingresso, poi spostati subito sul significato o sull applicazione davvero rilevante per il brand.',
                'shareability_driver' => 'Commento tempestivo ma con valore vero, non solo reazione.',
            ],
        ],
        'emotional-relatable' => [
            [
                'key' => 'shared_moment',
                'family' => 'relatable_scene',
                'platforms' => ['instagram', 'facebook', 'tiktok'],
                'formats' => ['reel', 'post', 'story', 'video'],
                'goals' => ['awareness', 'engagement', 'trust'],
                'trend_relevance' => ['low', 'medium'],
                'priority' => 0.87,
                'primary_template' => 'Ci sono momenti in cui {audience_label} vuole solo {desire_outcome}.',
                'alternative_template' => '{pain_statement}. Ed e proprio qui che {proof_focus}.',
                'narrative_template' => 'Parti da una scena, un gesto o una sensazione reale, poi trasformala in significato di brand senza diventare sdolcinato.',
                'shareability_driver' => 'Riconoscimento emotivo che invita a commentare o mandare il contenuto a qualcuno.',
            ],
            [
                'key' => 'human_detail',
                'family' => 'human_truth',
                'platforms' => ['instagram', 'facebook', 'linkedin'],
                'formats' => ['post', 'reel', 'video', 'story'],
                'goals' => ['trust', 'engagement', 'awareness'],
                'trend_relevance' => ['low', 'medium'],
                'priority' => 0.82,
                'primary_template' => '{curiosity_statement}. Spesso basta un dettaglio reale per cambiare come viene percepito {topic}.',
                'alternative_template' => 'Non serve alzare la voce per far passare {topic}: serve {proof_focus}.',
                'narrative_template' => 'Usa un dettaglio umano e concreto come ingresso, poi fai emergere la ragione piu profonda che lo rende memorabile.',
                'shareability_driver' => 'Dettaglio umano che aumenta riconoscimento e brand recall.',
            ],
        ],
        'conversion' => [
            [
                'key' => 'decision_before_offer',
                'family' => 'conversion_filter',
                'platforms' => ['instagram', 'facebook', 'linkedin'],
                'formats' => ['post', 'carousel', 'reel', 'video'],
                'goals' => ['lead', 'conversion'],
                'trend_relevance' => ['low', 'medium'],
                'priority' => 0.94,
                'primary_template' => 'Prima di scegliere {topic}, verifica {decision_filter}.',
                'alternative_template' => '{pain_statement}. Per evitarlo, parti da {proof_focus}.',
                'narrative_template' => 'Apri con il rischio o il filtro decisionale, mostra perche il brand e la scelta piu sensata e chiudi con next step morbido.',
                'shareability_driver' => 'Utilita decisionale che rende la CTA piu naturale.',
            ],
            [
                'key' => 'soft_offer_with_reason',
                'family' => 'offer_reason_why',
                'platforms' => ['instagram', 'facebook', 'linkedin'],
                'formats' => ['post', 'reel', 'carousel', 'story'],
                'goals' => ['lead', 'conversion'],
                'trend_relevance' => ['low', 'medium'],
                'priority' => 0.86,
                'primary_template' => 'Se oggi cerchi {desire_outcome}, ha senso guardare {proof_focus}.',
                'alternative_template' => 'La proposta giusta non spinge: chiarisce per chi e {topic}.',
                'narrative_template' => 'Parti dal bisogno vero, mostra il perche dell offerta e fai sentire la CTA come naturale conseguenza.',
                'shareability_driver' => 'Chiarezza di offerta senza tono promozionale aggressivo.',
            ],
        ],
        'social-proof' => [
            [
                'key' => 'real_scene_proof',
                'family' => 'proof_from_scene',
                'platforms' => ['instagram', 'facebook', 'linkedin'],
                'formats' => ['post', 'reel', 'carousel', 'video'],
                'goals' => ['trust', 'lead', 'engagement'],
                'trend_relevance' => ['low', 'medium'],
                'priority' => 0.91,
                'primary_template' => 'Quando {audience_label} vede {proof_focus}, capisce subito il livello di {topic}.',
                'alternative_template' => 'La prova migliore non e un claim: e {trust_proof}.',
                'narrative_template' => 'Apri con scena, risultato percepibile o feedback concreto, poi spiega perche quel segnale conta davvero.',
                'shareability_driver' => 'Prova riconoscibile che aumenta fiducia e passaparola.',
            ],
            [
                'key' => 'proof_with_takeaway',
                'family' => 'social_validation',
                'platforms' => ['instagram', 'facebook', 'linkedin'],
                'formats' => ['post', 'carousel', 'reel'],
                'goals' => ['trust', 'lead'],
                'trend_relevance' => ['low', 'medium'],
                'priority' => 0.84,
                'primary_template' => '{trust_proof}. E il motivo e piu semplice di quanto sembri.',
                'alternative_template' => 'Questa scena dice piu di qualsiasi claim su {topic}.',
                'narrative_template' => 'Parti da un segnale sociale credibile e leggibile, poi porta il contenuto su utilita, criterio o percezione reale del valore.',
                'shareability_driver' => 'Proof cue che rende il brand piu affidabile e memorabile.',
            ],
        ],
    ],

    'video_sequences' => [
        'authoritative' => [
            'hook_0_3' => 'Apri con errore frequente, contrasto o insight controintuitivo su {topic}.',
            'development_3_8' => 'Mostra subito il criterio concreto, il gesto tecnico o il dettaglio operativo che ribalta la scena.',
            'payoff_reveal' => 'Chiudi sul punto che fa percepire competenza e chiarezza decisionale.',
            'cta_ending' => 'Invita a salvare o a chiedere un confronto se il tema e rilevante.',
        ],
        'educational' => [
            'hook_0_3' => 'Apri con beneficio concreto o domanda utile legata a {topic}.',
            'development_3_8' => 'Semplifica in passaggio, checklist o micro-spiegazione visiva.',
            'payoff_reveal' => 'Lascia un takeaway immediatamente applicabile.',
            'cta_ending' => 'Chiudi con invito a salvare, condividere o approfondire.',
        ],
        'trend-aware' => [
            'hook_0_3' => 'Apri con pattern nativo o formato caldo, ma chiarisci il valore entro i primi tre secondi.',
            'development_3_8' => 'Trasforma il trend in un punto di vista o in un applicazione davvero coerente col brand.',
            'payoff_reveal' => 'Mostra il twist proprietario o la lettura che rende il trend utile.',
            'cta_ending' => 'Chiudi con comment trigger o invito leggero alla risposta.',
        ],
        'emotional-relatable' => [
            'hook_0_3' => 'Apri con gesto, espressione o momento umano che fa sentire subito la scena.',
            'development_3_8' => 'Fai emergere il significato o il bisogno emotivo senza rallentare il ritmo.',
            'payoff_reveal' => 'Chiudi sul dettaglio che rende il brand memorabile e vicino.',
            'cta_ending' => 'Invita a raccontare una esperienza simile o a mandare il video a qualcuno.',
        ],
        'conversion' => [
            'hook_0_3' => 'Apri con filtro decisionale, rischio o bisogno molto chiaro.',
            'development_3_8' => 'Mostra il perche dell offerta con prova, processo o differenza percepibile.',
            'payoff_reveal' => 'Rendi evidente il beneficio o il next step migliore.',
            'cta_ending' => 'Chiudi con CTA soft verso DM, click o richiesta info.',
        ],
        'social-proof' => [
            'hook_0_3' => 'Apri con scena reale, reazione o segnale sociale leggibile da subito.',
            'development_3_8' => 'Dai contesto al proof senza gonfiare il tono.',
            'payoff_reveal' => 'Fai emergere perche quella prova aumenta fiducia o desiderio.',
            'cta_ending' => 'Invita a salvare, commentare o chiedere dettagli se si riconoscono nella scena.',
        ],
    ],

    // ── Pattern virali aggiuntivi 2025-2026 ──────────────────────────────────
    // Questi pattern si affiancano ai pattern per strategy type.
    // Vengono usati dal ContentAngleEngine quando la piattaforma o il formato
    // li favorisce (es. reel TikTok → pov_pattern, carousel → myth_busting).

    'viral_patterns' => [
        [
            'key'                 => 'myth_busting',
            'family'              => 'myth_buster',
            'platforms'           => ['instagram', 'tiktok', 'linkedin', 'facebook'],
            'formats'             => ['post', 'reel', 'carousel', 'video'],
            'goals'               => ['awareness', 'engagement', 'trust'],
            'trend_relevance'     => ['medium', 'high'],
            'priority'            => 0.90,
            'primary_template'    => 'FALSO: {false_shortcut}. La realtà su {topic} è diversa da quello che si sente dire.',
            'alternative_template'=> 'Il mito più comune su {topic} — e cosa succede davvero.',
            'narrative_template'  => 'Identifica una credenza sbagliata comune nel settore. Ribaltala con prova o criterio concreto. Chiudi con il perché conta saperlo.',
            'shareability_driver' => 'Genera commenti di chi è d\'accordo e dissenso costruttivo. Alto reach.',
            'video_sequence'      => [
                'hook_0_3'        => 'Apri con la falsa credenza pronunciata o mostrata chiaramente.',
                'development_3_8' => 'Smaschera con prova, dato o confronto diretto.',
                'payoff_reveal'   => 'Mostra la versione corretta con criterio applicabile.',
                'cta_ending'      => 'Chiedi conferma nella sezione commenti o invita a salvare.',
            ],
        ],
        [
            'key'                 => 'before_after_story',
            'family'              => 'transformation_proof',
            'platforms'           => ['instagram', 'tiktok', 'facebook'],
            'formats'             => ['reel', 'post', 'video', 'carousel'],
            'goals'               => ['trust', 'conversion', 'awareness'],
            'trend_relevance'     => ['low', 'medium'],
            'priority'            => 0.88,
            'primary_template'    => 'Prima: {pain_statement}. Dopo: {desire_statement}.',
            'alternative_template'=> 'Come siamo passati da {topic} al risultato che vedi.',
            'narrative_template'  => 'Mostra lo stato prima con onestà. Racconta il processo reale. Concludi con il risultato visibile e il perché è replicabile.',
            'shareability_driver' => 'Proof visiva immediata. Altissimo save-rate e commenti di richiesta info.',
            'video_sequence'      => [
                'hook_0_3'        => 'Mostra lo stato "prima" in modo diretto e riconoscibile.',
                'development_3_8' => 'Racconta il passaggio chiave senza semplificare troppo.',
                'payoff_reveal'   => 'Mostra il risultato con chiarezza. Niente trucchi visivi.',
                'cta_ending'      => 'Invita a commentare con la loro situazione simile o chiedere info.',
            ],
        ],
        [
            'key'                 => 'pov_native',
            'family'              => 'pov_immersive',
            'platforms'           => ['tiktok', 'instagram'],
            'formats'             => ['reel', 'video'],
            'goals'               => ['engagement', 'awareness'],
            'trend_relevance'     => ['medium', 'high'],
            'priority'            => 0.87,
            'primary_template'    => 'POV: sei {audience_label} e stai affrontando {pain_statement}.',
            'alternative_template'=> 'POV: {desire_statement} — ecco come ci sei arrivato.',
            'narrative_template'  => 'Metti lo spettatore nella situazione. Descrivi la tensione. Porta il payoff che lui vorrebbe vivere.',
            'shareability_driver' => 'Immedesimazione totale. Altissimo completion rate quando il POV è preciso.',
            'video_sequence'      => [
                'hook_0_3'        => '"POV: ..." — entra subito nella situazione entro il primo secondo.',
                'development_3_8' => 'Sviluppa la scena con dettagli riconoscibili dall\'audience.',
                'payoff_reveal'   => 'Porta il twist, la soluzione o il momento di risoluzione.',
                'cta_ending'      => 'Chiudi con domanda che invita a condividere la propria esperienza.',
            ],
        ],
        [
            'key'                 => 'storytime_real',
            'family'              => 'narrative_storytime',
            'platforms'           => ['tiktok', 'instagram', 'facebook'],
            'formats'             => ['reel', 'video', 'post'],
            'goals'               => ['engagement', 'trust', 'awareness'],
            'trend_relevance'     => ['low', 'medium'],
            'priority'            => 0.89,
            'primary_template'    => '{authority_anchor}: questa cosa mi è capitata con {topic} e non me l\'aspettavo.',
            'alternative_template'=> 'La storia più strana (e più vera) che ho vissuto con {topic}.',
            'narrative_template'  => 'Inizio: contesto in 1-2 frasi. Tensione: il momento che ha cambiato qualcosa. Risoluzione: cosa è emerso. Lezione: perché conta per chi guarda.',
            'shareability_driver' => 'Narrative engagement. Le storie reali aumentano il dwell time e i commenti empatici.',
            'video_sequence'      => [
                'hook_0_3'        => 'Apri con la conseguenza o il momento di massima tensione della storia.',
                'development_3_8' => 'Costruisci il contesto e la progressione della vicenda.',
                'payoff_reveal'   => 'Rivela la risoluzione e la lezione implicita.',
                'cta_ending'      => 'Invita a condividere una loro storia simile nei commenti.',
            ],
        ],
        [
            'key'                 => 'numbers_list',
            'family'              => 'numbered_value_list',
            'platforms'           => ['instagram', 'linkedin', 'tiktok'],
            'formats'             => ['carousel', 'reel', 'post'],
            'goals'               => ['awareness', 'trust', 'engagement'],
            'trend_relevance'     => ['low', 'medium'],
            'priority'            => 0.86,
            'primary_template'    => 'X {desire_outcome} senza {false_shortcut}: la lista che salvi.',
            'alternative_template'=> 'X segnali che {pain_statement} — e come uscirne.',
            'narrative_template'  => 'Lista numerata concisa. Ogni punto vale da solo. Chiudi con il punto più sorprendente o quello che di solito viene ignorato.',
            'shareability_driver' => 'Format ad alta leggibilità. Save-rate elevato su contenuto denso e schematico.',
            'video_sequence'      => [
                'hook_0_3'        => 'Annuncia il numero e il tema con chiarezza totale.',
                'development_3_8' => 'Scansiona i punti con ritmo visivo veloce e testo leggibile.',
                'payoff_reveal'   => 'Il punto finale deve essere il più inaspettato o il più utile.',
                'cta_ending'      => 'Invita a salvare o a commentare con quale punto li ha colpiti di più.',
            ],
        ],
        [
            'key'                 => 'unpopular_take',
            'family'              => 'contrarian_insight',
            'platforms'           => ['linkedin', 'instagram', 'tiktok'],
            'formats'             => ['post', 'reel', 'video'],
            'goals'               => ['engagement', 'awareness', 'trust'],
            'trend_relevance'     => ['medium', 'high'],
            'priority'            => 0.88,
            'primary_template'    => 'Posizione netta su {topic}: {authority_reframe}.',
            'alternative_template'=> 'Non è popolare dirlo, ma {proof_focus} cambia tutto su {topic}.',
            'narrative_template'  => 'Prendi una posizione controintuitiva ma difendibile. Spiega il ragionamento. Chiudi con un invito al confronto, non all\'accordo cieco.',
            'shareability_driver' => 'Polarizza. Chi è d\'accordo condivide, chi non lo è commenta. Reach molto alto.',
            'video_sequence'      => [
                'hook_0_3'        => '"Hot take:", "Unpopular opinion:" — dichiara la posizione entro 2 secondi.',
                'development_3_8' => 'Argomentazione concisa e specifica. Evita il vago.',
                'payoff_reveal'   => 'Chiudi con l\'implicazione pratica, non con la ripetizione della tesi.',
                'cta_ending'      => 'Chiedi esplicitamente l\'opinione contraria. Il dissenso gestito aumenta il reach.',
            ],
        ],
    ],

    'authority_signal_templates' => [
        'operational_detail' => 'Dettaglio operativo reale su {topic}, non claim astratto.',
        'decision_criterion' => 'Criterio chiaro per valutare {topic} con maggiore lucidita.',
        'field_experience' => 'Osservazione di campo che fa percepire esperienza reale con {topic}.',
        'professional_standard' => 'Standard qualitativo o metodo che il brand applica davvero su {topic}.',
    ],

    'trust_signal_templates' => [
        'observable_proof' => 'Segnale osservabile, scena reale o evidenza concreta legata a {topic}.',
        'human_cue' => 'Presenza umana autentica o situazione riconoscibile per {audience_label}.',
        'specific_constraint' => 'Dettaglio specifico che rende il messaggio credibile e non generico.',
        'social_validation' => 'Indicatore di fiducia o soddisfazione raccontato senza inventare numeri.',
    ],
];
