<?php

return [
    'version' => 'content_overlay_system_v1',
    'default_mode' => 'auto',
    'fonts' => [
        'segoe_ui' => [
            'label' => 'Segoe UI',
            'css_stack' => '"Segoe UI", Arial, sans-serif',
            'fallback_family' => 'arial',
            'regular_paths' => [
                'C:\\Windows\\Fonts\\segoeui.ttf',
                '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
                '/Library/Fonts/Arial.ttf',
            ],
            'bold_paths' => [
                'C:\\Windows\\Fonts\\segoeuib.ttf',
                '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf',
                '/Library/Fonts/Arial Bold.ttf',
            ],
        ],
        'arial' => [
            'label' => 'Arial',
            'css_stack' => 'Arial, Helvetica, sans-serif',
            'fallback_family' => 'segoe_ui',
            'regular_paths' => [
                'C:\\Windows\\Fonts\\arial.ttf',
                '/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf',
                '/Library/Fonts/Arial.ttf',
            ],
            'bold_paths' => [
                'C:\\Windows\\Fonts\\arialbd.ttf',
                '/usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf',
                '/Library/Fonts/Arial Bold.ttf',
            ],
        ],
        'bahnschrift' => [
            'label' => 'Bahnschrift',
            'css_stack' => 'Bahnschrift, Arial, sans-serif',
            'fallback_family' => 'arial',
            'regular_paths' => [
                'C:\\Windows\\Fonts\\bahnschrift.ttf',
                '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
            ],
            'bold_paths' => [
                'C:\\Windows\\Fonts\\bahnschrift.ttf',
                '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf',
            ],
        ],
        'trebuchet_ms' => [
            'label' => 'Trebuchet MS',
            'css_stack' => '"Trebuchet MS", Arial, sans-serif',
            'fallback_family' => 'arial',
            'regular_paths' => [
                'C:\\Windows\\Fonts\\trebuc.ttf',
                '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
            ],
            'bold_paths' => [
                'C:\\Windows\\Fonts\\trebucbd.ttf',
                '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf',
            ],
        ],
        'georgia' => [
            'label' => 'Georgia',
            'css_stack' => 'Georgia, "Times New Roman", serif',
            'fallback_family' => 'arial',
            'regular_paths' => [
                'C:\\Windows\\Fonts\\georgia.ttf',
                '/usr/share/fonts/truetype/liberation2/LiberationSerif-Regular.ttf',
                '/Library/Fonts/Georgia.ttf',
            ],
            'bold_paths' => [
                'C:\\Windows\\Fonts\\georgiab.ttf',
                '/usr/share/fonts/truetype/liberation2/LiberationSerif-Bold.ttf',
                '/Library/Fonts/Georgia Bold.ttf',
            ],
        ],
        'impact' => [
            'label' => 'Impact',
            'css_stack' => 'Impact, "Arial Black", sans-serif',
            'fallback_family' => 'arial',
            'regular_paths' => [
                'C:\\Windows\\Fonts\\impact.ttf',
                '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf',
            ],
            'bold_paths' => [
                'C:\\Windows\\Fonts\\impact.ttf',
                '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf',
            ],
        ],
    ],
    'tone_presets' => [
        'premium' => ['label' => 'Premium', 'font_family' => 'georgia', 'fallback_family' => 'arial', 'preset' => 'premium_title_card'],
        'bold' => ['label' => 'Bold', 'font_family' => 'impact', 'fallback_family' => 'arial', 'preset' => 'bold_hook_banner'],
        'editorial' => ['label' => 'Editorial', 'font_family' => 'georgia', 'fallback_family' => 'arial', 'preset' => 'editorial_quote_card'],
        'modern' => ['label' => 'Modern', 'font_family' => 'bahnschrift', 'fallback_family' => 'arial', 'preset' => 'modern_split_caption'],
        'minimal' => ['label' => 'Minimal', 'font_family' => 'segoe_ui', 'fallback_family' => 'arial', 'preset' => 'minimal_clean_stat'],
        'energetic' => ['label' => 'Energetic', 'font_family' => 'trebuchet_ms', 'fallback_family' => 'arial', 'preset' => 'energetic_launch'],
    ],
    'presets' => [
        'premium_title_card' => [
            'label' => 'Premium Title Card',
            'tone' => 'premium',
            'font_weight' => '700',
            'font_size_mode' => 'large',
            'text_case' => 'sentence',
            'alignment' => 'left',
            'position' => 'upper_left',
            'safe_area' => 'upper_third',
            'max_lines' => 3,
            'color' => '#FFFFFF',
            'stroke_color' => '#102033',
            'shadow' => true,
            'background_style' => 'dark_box',
            'animation_style' => 'fade',
        ],
        'bold_hook_banner' => [
            'label' => 'Bold Hook Banner',
            'tone' => 'bold',
            'font_weight' => '800',
            'font_size_mode' => 'xl',
            'text_case' => 'uppercase',
            'alignment' => 'center',
            'position' => 'upper_center',
            'safe_area' => 'upper_third',
            'max_lines' => 2,
            'color' => '#FFFFFF',
            'stroke_color' => '#0B1320',
            'shadow' => true,
            'background_style' => 'dark_box',
            'animation_style' => 'pop',
        ],
        'editorial_quote_card' => [
            'label' => 'Editorial Quote Card',
            'tone' => 'editorial',
            'font_weight' => '700',
            'font_size_mode' => 'large',
            'text_case' => 'title',
            'alignment' => 'left',
            'position' => 'center_left',
            'safe_area' => 'center_safe',
            'max_lines' => 3,
            'color' => '#FFFFFF',
            'stroke_color' => '#0F172A',
            'shadow' => true,
            'background_style' => 'dark_box',
            'animation_style' => 'fade',
        ],
        'modern_split_caption' => [
            'label' => 'Modern Split Caption',
            'tone' => 'modern',
            'font_weight' => '700',
            'font_size_mode' => 'large',
            'text_case' => 'sentence',
            'alignment' => 'left',
            'position' => 'lower_left',
            'safe_area' => 'lower_third',
            'max_lines' => 3,
            'color' => '#FFFFFF',
            'stroke_color' => '#0F172A',
            'shadow' => true,
            'background_style' => 'gradient_strip',
            'animation_style' => 'slide_up',
        ],
        'minimal_clean_stat' => [
            'label' => 'Minimal Clean Stat',
            'tone' => 'minimal',
            'font_weight' => '600',
            'font_size_mode' => 'medium',
            'text_case' => 'sentence',
            'alignment' => 'left',
            'position' => 'upper_left',
            'safe_area' => 'upper_third',
            'max_lines' => 2,
            'color' => '#FFFFFF',
            'stroke_color' => '#111827',
            'shadow' => false,
            'background_style' => 'none',
            'animation_style' => 'fade',
        ],
        'energetic_launch' => [
            'label' => 'Energetic Launch',
            'tone' => 'energetic',
            'font_weight' => '800',
            'font_size_mode' => 'xl',
            'text_case' => 'uppercase',
            'alignment' => 'center',
            'position' => 'center',
            'safe_area' => 'center_safe',
            'max_lines' => 2,
            'color' => '#FFFFFF',
            'stroke_color' => '#0F172A',
            'shadow' => true,
            'background_style' => 'dark_box',
            'animation_style' => 'pop',
        ],
        'cta_outro_card' => [
            'label' => 'CTA Outro Card',
            'tone' => 'modern',
            'font_weight' => '700',
            'font_size_mode' => 'medium',
            'text_case' => 'sentence',
            'alignment' => 'center',
            'position' => 'lower_center',
            'safe_area' => 'lower_third',
            'max_lines' => 2,
            'color' => '#FFFFFF',
            'stroke_color' => '#0F172A',
            'shadow' => true,
            'background_style' => 'dark_box',
            'animation_style' => 'fade',
        ],
    ],
    'platform_rules' => [
        'instagram' => ['position' => 'upper_left', 'safe_area' => 'upper_third', 'max_lines' => 3, 'font_size_mode' => 'large'],
        'facebook' => ['position' => 'upper_left', 'safe_area' => 'upper_third', 'max_lines' => 3, 'font_size_mode' => 'medium'],
        'linkedin' => ['position' => 'upper_left', 'safe_area' => 'upper_third', 'max_lines' => 3, 'font_size_mode' => 'medium'],
        'tiktok' => ['position' => 'upper_center', 'safe_area' => 'upper_third', 'max_lines' => 2, 'font_size_mode' => 'xl'],
        'youtube' => ['position' => 'center_left', 'safe_area' => 'center_safe', 'max_lines' => 2, 'font_size_mode' => 'large'],
        'threads' => ['position' => 'upper_left', 'safe_area' => 'upper_third', 'max_lines' => 3, 'font_size_mode' => 'medium'],
    ],
    'video_defaults' => [
        'intro_duration_ms' => 3000,
        'development_start_ms' => 3000,
        'development_end_ms' => 8000,
        'outro_duration_ms' => 2500,
    ],
    'ui' => [
        'modes' => ['auto', 'manual', 'off'],
        'font_weights' => ['400', '500', '600', '700', '800'],
        'font_size_modes' => ['small', 'medium', 'large', 'xl'],
        'text_cases' => ['sentence', 'title', 'uppercase'],
        'alignments' => ['left', 'center', 'right'],
        'positions' => ['upper_left', 'upper_center', 'center_left', 'center', 'lower_left', 'lower_center'],
        'safe_areas' => ['upper_third', 'center_safe', 'lower_third'],
        'background_styles' => ['none', 'dark_box', 'light_box', 'gradient_strip'],
        'animation_styles' => ['none', 'fade', 'pop', 'slide_up'],
    ],
];
