<?php

return [
    'enabled' => env('TREND_INTELLIGENCE_ENABLED', env('EDITORIAL_TREND_ENABLED', true)),
    'ttl_minutes' => (int) env('TREND_INTELLIGENCE_TTL_MINUTES', 240),
    'max_opportunities' => (int) env('TREND_INTELLIGENCE_MAX_OPPORTUNITIES', 6),
    'min_brand_fit_score' => (float) env('TREND_INTELLIGENCE_MIN_BRAND_FIT', 0.55),
    'min_relevance_score' => (float) env('TREND_INTELLIGENCE_MIN_RELEVANCE', 0.58),
    'max_posts_per_plan' => (int) env('TREND_INTELLIGENCE_MAX_POSTS_PER_PLAN', env('EDITORIAL_TREND_MAX_POSTS', 2)),
    'risk_block_flags' => [
        'policy_risk',
        'reputation_risk',
        'brand_conflict',
    ],
    'adapters' => [
        ['driver' => 'config_seed'],
    ],
    'seed_signals' => [
        [
            'platform' => 'instagram',
            'topic' => 'micro case study transformation',
            'format_type' => 'reel',
            'hook_patterns' => [
                'Apri con il prima della scena reale e chiudi con il takeaway pratico.',
                'Mostra il dettaglio che cambia la percezione nei primi due secondi.',
            ],
            'style_notes' => [
                'Montaggio rapido ma premium, senza caos visivo.',
                'Usa ambienti, persone o prodotti reali del brand come ancora narrativa.',
            ],
            'freshness_score' => 0.84,
            'saturation_score' => 0.46,
            'risk_flags' => [],
            'source_type' => 'config_seed',
            'industries' => ['retail', 'hospitality', 'restaurant', 'beauty', 'real_estate'],
            'audiences' => ['consumer', 'local', 'premium'],
            'goals' => ['awareness', 'engagement'],
            'tags' => ['professional', 'case-study', 'social-proof'],
            'requires' => ['real_visual_anchor'],
        ],
        [
            'platform' => 'instagram',
            'topic' => 'saveable checklist carousel',
            'format_type' => 'carousel',
            'hook_patterns' => [
                'Apri con una promessa molto concreta e salva-friendly.',
                'Usa un titolo breve che sembri una check-list da conservare.',
            ],
            'style_notes' => [
                'Gerarchia chiara slide per slide.',
                'Taglio professionale e utile, niente clickbait vuoto.',
            ],
            'freshness_score' => 0.72,
            'saturation_score' => 0.52,
            'risk_flags' => [],
            'source_type' => 'config_seed',
            'industries' => ['saas', 'consulting', 'wellness', 'beauty', 'retail'],
            'audiences' => ['b2b', 'consumer'],
            'goals' => ['saves', 'authority'],
            'tags' => ['educational', 'saveable', 'professional'],
            'requires' => ['overlay_support'],
        ],
        [
            'platform' => 'instagram',
            'topic' => 'founder or expert point of view',
            'format_type' => 'reel',
            'hook_patterns' => [
                'Apri con una verita controintuitiva detta dalla persona reale del brand.',
                'Usa una scena POV breve e una frase che sembri vissuta, non recitata.',
            ],
            'style_notes' => [
                'Volto reale e delivery sobrio.',
                'Funziona bene se l identita persona e forte e consistente.',
            ],
            'freshness_score' => 0.78,
            'saturation_score' => 0.41,
            'risk_flags' => [],
            'source_type' => 'config_seed',
            'industries' => ['saas', 'consulting', 'wellness', 'beauty', 'real_estate'],
            'audiences' => ['b2b', 'consumer', 'local'],
            'goals' => ['trust', 'engagement'],
            'tags' => ['human-led', 'trust', 'professional'],
            'requires' => ['person_identity'],
        ],
        [
            'platform' => 'tiktok',
            'topic' => 'trend audio imitation meme',
            'format_type' => 'reel',
            'hook_patterns' => [
                'Replica audio di trend con battuta virale.',
            ],
            'style_notes' => [
                'Ritmo memetico e ironia spinta.',
            ],
            'freshness_score' => 0.88,
            'saturation_score' => 0.82,
            'risk_flags' => ['brand_conflict', 'meme_overload'],
            'source_type' => 'config_seed',
            'industries' => ['generic'],
            'audiences' => ['broad'],
            'goals' => ['engagement'],
            'tags' => ['meme', 'casual'],
            'requires' => [],
        ],
        [
            'platform' => 'linkedin',
            'topic' => 'operator insight with practical lesson',
            'format_type' => 'post',
            'hook_patterns' => [
                'Apri con un osservazione reale dal lavoro quotidiano.',
                'Porta subito il micro insight e chiudi con applicazione pratica.',
            ],
            'style_notes' => [
                'Tono competente ma non professorale.',
                'Ottimo per autorevolezza e commenti qualificati.',
            ],
            'freshness_score' => 0.69,
            'saturation_score' => 0.37,
            'risk_flags' => [],
            'source_type' => 'config_seed',
            'industries' => ['saas', 'consulting', 'real_estate', 'professional_services'],
            'audiences' => ['b2b', 'decision_makers'],
            'goals' => ['authority', 'leads'],
            'tags' => ['insight', 'authority', 'professional'],
            'requires' => [],
        ],
        [
            'platform' => 'facebook',
            'topic' => 'community story anchored in a real place',
            'format_type' => 'post',
            'hook_patterns' => [
                'Apri con una scena di vita reale riconoscibile dalla community.',
                'Usa un dettaglio locale o relazionale che inviti commenti autentici.',
            ],
            'style_notes' => [
                'Calore umano, foto o video grounded, tono inclusivo.',
            ],
            'freshness_score' => 0.66,
            'saturation_score' => 0.28,
            'risk_flags' => [],
            'source_type' => 'config_seed',
            'industries' => ['restaurant', 'hospitality', 'retail', 'wellness'],
            'audiences' => ['local', 'community'],
            'goals' => ['engagement', 'trust'],
            'tags' => ['community', 'local', 'storytelling'],
            'requires' => ['real_location_anchor'],
        ],
    ],
];