<?php

return [
    'enabled' => env('TREND_INTELLIGENCE_ENABLED', env('EDITORIAL_TREND_ENABLED', true)),
    'ttl_minutes' => (int) env('TREND_INTELLIGENCE_TTL_MINUTES', 240),
    'max_opportunities' => (int) env('TREND_INTELLIGENCE_MAX_OPPORTUNITIES', 6),
    'performance_window_days' => (int) env('TREND_INTELLIGENCE_PERFORMANCE_WINDOW_DAYS', 90),
    'max_signals_per_adapter' => (int) env('TREND_INTELLIGENCE_MAX_SIGNALS_PER_ADAPTER', 4),
    'min_brand_fit_score' => (float) env('TREND_INTELLIGENCE_MIN_BRAND_FIT', 0.55),
    'min_relevance_score' => (float) env('TREND_INTELLIGENCE_MIN_RELEVANCE', 0.58),
    'max_posts_per_plan' => (int) env('TREND_INTELLIGENCE_MAX_POSTS_PER_PLAN', env('EDITORIAL_TREND_MAX_POSTS', 2)),
    'risk_block_flags' => [
        'policy_risk',
        'reputation_risk',
        'brand_conflict',
    ],
    'adapters' => [
        ['driver' => 'internal_performance'],
        ['driver' => 'hashtag_patterns'],
        ['driver' => 'editorial_memory'],
        ['driver' => 'curated_manual'],
        ['driver' => 'creator_best_practice'],
        ['driver' => 'config_seed'],
    ],
    'curated_manual_signals' => [
        [
            'platform' => 'instagram',
            'topic' => 'evidence-led founder take',
            'title' => 'Founder take backed by a real operating detail',
            'summary' => 'Instagram continua a premiare hook autorevoli che partono da un osservazione reale del founder o dell esperto e la trasformano in un takeaway concreto.',
            'format_type' => 'reel',
            'hook_patterns' => [
                'Apri con una frase netta, reale e non teatrale nei primi due secondi.',
                'Mostra subito volto o contesto reale e poi porta il punto utile.',
            ],
            'style_notes' => [
                'Tono competente e sobrio.',
                'Il dettaglio operativo deve arrivare prima della CTA.',
            ],
            'freshness_score' => 0.84,
            'confidence_score' => 0.76,
            'saturation_score' => 0.40,
            'risk_flags' => [],
            'source_ref' => 'curated:instagram:founder-take',
            'industries' => ['saas', 'consulting', 'professional_services', 'real_estate'],
            'audiences' => ['b2b', 'founders', 'decision_makers'],
            'goals' => ['trust', 'engagement', 'authority'],
            'tags' => ['founder', 'authority', 'human-led'],
            'requires' => ['person_identity'],
            'evidence_payload' => [
                'artifact_type' => 'curated_manual_entry',
                'curation_note' => 'Pattern manuale usato quando il brand ha una persona forte e vuole aumentare fiducia senza tono guru.',
            ],
        ],
        [
            'platform' => 'instagram',
            'topic' => 'saveable checklist carousel',
            'title' => 'Saveable carousel with one practical checklist',
            'summary' => 'I caroselli che promettono una checklist concreta e restano puliti a livello visivo continuano a reggere bene su Instagram per PMI e servizi.',
            'format_type' => 'carousel',
            'hook_patterns' => [
                'Apri con una promessa molto concreta e salva-friendly.',
                'Usa un titolo che sembra una checklist immediatamente utile.',
            ],
            'style_notes' => [
                'Una idea centrale per carosello.',
                'Overlay puliti e leggibili anche su mobile.',
            ],
            'freshness_score' => 0.78,
            'confidence_score' => 0.73,
            'saturation_score' => 0.48,
            'risk_flags' => [],
            'source_ref' => 'curated:instagram:checklist-carousel',
            'industries' => ['saas', 'consulting', 'beauty', 'wellness', 'retail'],
            'audiences' => ['b2b', 'consumer'],
            'goals' => ['saves', 'authority'],
            'tags' => ['educational', 'saveable', 'checklist'],
            'requires' => ['overlay_support'],
            'evidence_payload' => [
                'artifact_type' => 'curated_manual_entry',
                'curation_note' => 'Pattern manuale pensato per contenuti da salvare e consultare.',
            ],
        ],
    ],
    'creator_best_practice_signals' => [
        [
            'platform' => 'instagram',
            'topic' => 'first two second visual anchor',
            'title' => 'Anchor the reel in the first two seconds',
            'summary' => 'Per i reel Instagram performanti il primo frame deve chiarire subito chi parla o cosa si vede: volto, prodotto o dettaglio chiave.',
            'format_type' => 'reel',
            'hook_patterns' => [
                'Mostra volto o prodotto gia nel primo frame.',
                'La prima frase deve essere comprensibile anche senza audio.',
            ],
            'style_notes' => [
                'Un solo messaggio principale.',
                'Evita intro generiche o scene senza contesto.',
            ],
            'freshness_score' => 0.88,
            'confidence_score' => 0.82,
            'saturation_score' => 0.35,
            'risk_flags' => [],
            'source_ref' => 'creator-note:instagram:first-two-second-anchor',
            'industries' => ['generic'],
            'audiences' => ['broad'],
            'goals' => ['engagement', 'watch_time'],
            'tags' => ['reel', 'hook', 'first-seconds'],
            'requires' => ['real_visual_anchor'],
            'evidence_payload' => [
                'artifact_type' => 'creator_best_practice_note',
                'note' => 'Best practice ricorrente: apri con il soggetto vero e una promessa chiara.',
            ],
        ],
        [
            'platform' => 'instagram',
            'topic' => 'single idea reel with reveal before second eight',
            'title' => 'Single-idea reel with reveal before second eight',
            'summary' => 'I reel piu leggibili tengono una sola idea e mostrano payoff o reveal prima dell ottavo secondo.',
            'format_type' => 'reel',
            'hook_patterns' => [
                'Promessa semplice nei primi secondi.',
                'Reveal chiaro entro il secondo otto.',
            ],
            'style_notes' => [
                'Nessun giro largo iniziale.',
                'CTA breve e finale, non anticipata.',
            ],
            'freshness_score' => 0.85,
            'confidence_score' => 0.79,
            'saturation_score' => 0.38,
            'risk_flags' => [],
            'source_ref' => 'creator-note:instagram:single-idea-reveal',
            'industries' => ['generic'],
            'audiences' => ['broad'],
            'goals' => ['watch_time', 'engagement'],
            'tags' => ['reel', 'structure', 'payoff'],
            'requires' => [],
            'evidence_payload' => [
                'artifact_type' => 'creator_best_practice_note',
                'note' => 'Best practice strutturale: una sola idea forte, payoff rapido, chiusura pulita.',
            ],
        ],
    ],
    'hashtag_pattern_artifacts' => [
        [
            'topic' => 'micro case study transformation',
            'title' => 'Transformation and before-after pattern',
            'format_type' => 'reel',
            'hashtags' => ['#beforeafter', '#transformation', '#result', '#makeover', '#caseStudy'],
            'hook_patterns' => [
                'Apri dal prima e mostra il dettaglio che cambia la percezione.',
                'Taglia subito sul risultato reale, poi spiega il perche.',
            ],
            'style_notes' => [
                'Funziona se il risultato e reale e dimostrabile.',
                'Evita estetica troppo urlata.',
            ],
            'niche_tags' => ['beauty', 'wellness', 'retail', 'real_estate'],
            'risk_flags' => [],
        ],
        [
            'topic' => 'saveable checklist carousel',
            'title' => 'Checklist and how-to hashtag cluster',
            'format_type' => 'carousel',
            'hashtags' => ['#tips', '#howto', '#checklist', '#guide', '#savethis', '#consigli'],
            'hook_patterns' => [
                'Apri con una promessa pratica da salvare.',
                'Dichiara subito che si tratta di una checklist o guida breve.',
            ],
            'style_notes' => [
                'Gerarchia tipografica chiara.',
                'Ogni slide deve essere autonoma.',
            ],
            'niche_tags' => ['saas', 'consulting', 'professional_services', 'beauty'],
            'risk_flags' => [],
        ],
        [
            'topic' => 'founder or expert point of view',
            'title' => 'Expert POV hashtag cluster',
            'format_type' => 'reel',
            'hashtags' => ['#founder', '#expert', '#behindthescenes', '#team', '#dayinthelife'],
            'hook_patterns' => [
                'Apri con una verita vissuta detta dalla persona reale del brand.',
                'Mostra subito chi parla e perche vale ascoltarlo.',
            ],
            'style_notes' => [
                'Delivery naturale, non recitata.',
                'Il POV deve restare utile, non autoreferenziale.',
            ],
            'niche_tags' => ['saas', 'consulting', 'professional_services', 'real_estate'],
            'risk_flags' => [],
        ],
    ],
    'seed_signals' => [
        [
            'platform' => 'instagram',
            'topic' => 'micro case study transformation',
            'format_type' => 'reel',
            'hook_patterns' => [
                'Apri con il prima della scena reale e chiudi con il takeaway pratico.',
                'Mostra il dettaglio che cambia la percezione nei primi due secondi.',
            ],
            'style_notes' => [
                'Montaggio rapido ma premium, senza caos visivo.',
                'Usa ambienti, persone o prodotti reali del brand come ancora narrativa.',
            ],
            'freshness_score' => 0.84,
            'saturation_score' => 0.46,
            'risk_flags' => [],
            'source_type' => 'config_seed',
            'industries' => ['retail', 'hospitality', 'restaurant', 'beauty', 'real_estate'],
            'audiences' => ['consumer', 'local', 'premium'],
            'goals' => ['awareness', 'engagement'],
            'tags' => ['professional', 'case-study', 'social-proof'],
            'requires' => ['real_visual_anchor'],
        ],
        [
            'platform' => 'instagram',
            'topic' => 'saveable checklist carousel',
            'format_type' => 'carousel',
            'hook_patterns' => [
                'Apri con una promessa molto concreta e salva-friendly.',
                'Usa un titolo breve che sembri una check-list da conservare.',
            ],
            'style_notes' => [
                'Gerarchia chiara slide per slide.',
                'Taglio professionale e utile, niente clickbait vuoto.',
            ],
            'freshness_score' => 0.72,
            'saturation_score' => 0.52,
            'risk_flags' => [],
            'source_type' => 'config_seed',
            'industries' => ['saas', 'consulting', 'wellness', 'beauty', 'retail'],
            'audiences' => ['b2b', 'consumer'],
            'goals' => ['saves', 'authority'],
            'tags' => ['educational', 'saveable', 'professional'],
            'requires' => ['overlay_support'],
        ],
        [
            'platform' => 'instagram',
            'topic' => 'founder or expert point of view',
            'format_type' => 'reel',
            'hook_patterns' => [
                'Apri con una verita controintuitiva detta dalla persona reale del brand.',
                'Usa una scena POV breve e una frase che sembri vissuta, non recitata.',
            ],
            'style_notes' => [
                'Volto reale e delivery sobrio.',
                'Funziona bene se l identita persona e forte e consistente.',
            ],
            'freshness_score' => 0.78,
            'saturation_score' => 0.41,
            'risk_flags' => [],
            'source_type' => 'config_seed',
            'industries' => ['saas', 'consulting', 'wellness', 'beauty', 'real_estate'],
            'audiences' => ['b2b', 'consumer', 'local'],
            'goals' => ['trust', 'engagement'],
            'tags' => ['human-led', 'trust', 'professional'],
            'requires' => ['person_identity'],
        ],
        [
            'platform' => 'tiktok',
            'topic' => 'trend audio imitation meme',
            'format_type' => 'reel',
            'hook_patterns' => [
                'Replica audio di trend con battuta virale.',
            ],
            'style_notes' => [
                'Ritmo memetico e ironia spinta.',
            ],
            'freshness_score' => 0.88,
            'saturation_score' => 0.82,
            'risk_flags' => ['brand_conflict', 'meme_overload'],
            'source_type' => 'config_seed',
            'industries' => ['generic'],
            'audiences' => ['broad'],
            'goals' => ['engagement'],
            'tags' => ['meme', 'casual'],
            'requires' => [],
        ],
        [
            'platform' => 'linkedin',
            'topic' => 'operator insight with practical lesson',
            'format_type' => 'post',
            'hook_patterns' => [
                'Apri con un osservazione reale dal lavoro quotidiano.',
                'Porta subito il micro insight e chiudi con applicazione pratica.',
            ],
            'style_notes' => [
                'Tono competente ma non professorale.',
                'Ottimo per autorevolezza e commenti qualificati.',
            ],
            'freshness_score' => 0.69,
            'saturation_score' => 0.37,
            'risk_flags' => [],
            'source_type' => 'config_seed',
            'industries' => ['saas', 'consulting', 'real_estate', 'professional_services'],
            'audiences' => ['b2b', 'decision_makers'],
            'goals' => ['authority', 'leads'],
            'tags' => ['insight', 'authority', 'professional'],
            'requires' => [],
        ],
        [
            'platform' => 'facebook',
            'topic' => 'community story anchored in a real place',
            'format_type' => 'post',
            'hook_patterns' => [
                'Apri con una scena di vita reale riconoscibile dalla community.',
                'Usa un dettaglio locale o relazionale che inviti commenti autentici.',
            ],
            'style_notes' => [
                'Calore umano, foto o video grounded, tono inclusivo.',
            ],
            'freshness_score' => 0.66,
            'saturation_score' => 0.28,
            'risk_flags' => [],
            'source_type' => 'config_seed',
            'industries' => ['restaurant', 'hospitality', 'retail', 'wellness'],
            'audiences' => ['local', 'community'],
            'goals' => ['engagement', 'trust'],
            'tags' => ['community', 'local', 'storytelling'],
            'requires' => ['real_location_anchor'],
        ],
    ],
];
